- block:
  - name: 创建 cni 相关目录
    file: 
      name: "{{ item }}"
      state: directory
    with_items:
    - /etc/cni/net.d
    - /etc/kubernetes/addons/network-plugin

  - include_tasks: flannel.yaml
    when: network_plugin == 'flannel'

  - include_tasks: calico.yaml
    when: network_plugin == 'calico'
    
  when: network_plugin_enabled|bool