# 校验节点软件系统及硬件系统、安装必要基础组件、docker、kubeadm、kubelet、kubectl
- hosts: 
  - new-master
  roles:
  - prepare/base
  - prepare/docker
  - prepare/kubernetes

# 进行apiserver负载均衡
- hosts: 
  - all
  roles:
  - role: load-balancer
    when: 
    - (groups['kube-master']|length + groups['new-master']|length) > 1 
    - lb_mode != 'slb'

# 初始化master节点
- hosts: 
  - etcd
  - kube-master
  - new-master
  roles:
  - etcd
  - kube-master/certificates
  - kube-master/install
  - kube-worker

# 标记各节点角色
- hosts: 
  - new-master
  roles:
  - post