- hosts: 
  - etcd[0]
  tasks:
  - name: 校验 kube_upgrade_version 是否设置
    run_once: true
    assert:
      that: kube_upgrade_version is defined
      msg: "请设置变量 kube_upgrade_version。"

- hosts: 
  - etcd[0]
  - kube-master
  - kube-worker
  - new-master
  - new-worker
  roles:
  - backup

- hosts:
  - kube-master
  - kube-worker
  - new-master
  - new-worker
  serial: 1
  roles:
  - upgrade

- hosts: 
  - etcd
  - new-etcd
  - kube-master
  - new-master
  roles:
  - etcd/certificates
  - kube-master/certificates