# 提权操作
ansible_become: true
command_warnings: false
# 安装模式
install_mode: online
# 是否跳过节点资源校验
skip_verify_node: false
# 默认apiserver负载类型
lb_mode: nginx
# CentOS
epel_yum_repo: http://mirrors.aliyun.com/epel/7/$basearch
# 默认kube_dns_domain
kube_dns_domain: cluster.local
# 默认 lb_kube_apiserver_port
lb_kube_apiserver_port: 8443