# 提权操作
ansible_become: true
# 是否启用网络组建
network_plugin_enabled: true
# 集群网络插件，目前支持flannel,calico
network_plugin: "flannel"
# 集群pod ip段
kube_pod_subnet: 10.244.0.0/18

# 负载后的apiserver端口号
lb_kube_apiserver_port: 8443
KUBE_APISERVER_PORT: >-
  {% if (groups['kube-master']|length + groups['new-master']|length) == 1 %}
    6443
  {% else %}
    {{ lb_kube_apiserver_port }}
  {% endif %}

# apiserver ip
KUBE_APISERVER_IP: >-
  {% if (groups['kube-master']|length + groups['new-master']|length) == 1 %}
    {% if hostvars[groups['kube-master']|first]['ansible_host'] is defined %}
      {{ hostvars[groups['kube-master']|first]['ansible_host'] }}
    {% else %}
      {{ groups['kube-master']|first }}
    {% endif %}
  {% else %}
    {% if lb_kube_apiserver_ip is not defined %}
      127.0.0.1
    {% else %}
      {{ lb_kube_apiserver_ip }}
    {% endif %}
  {% endif %}

# 设置 flannel 后端
# flannel_backend: "host-gw"
flannel_backend: "vxlan"
# flannel 镜像地址
flannel_image: quay.azk8s.cn/coreos/flannel:v0.10.0-amd64
# 选择默认网卡
flannel_iface: true

# calico mtu
calico_veth_mtu: 1440
# calico 相关镜像
calico_typha_image: dockerhub.azk8s.cn/calico/typha:v3.7.2
calico_cni_image: dockerhub.azk8s.cn/calico/cni:v3.7.2
calico_node_image: dockerhub.azk8s.cn/calico/node:v3.7.2
calico_kube_controllers_image: dockerhub.azk8s.cn/calico/kube-controllers:v3.7.2
# 设置 Felix 日志级别(debug, info, warning, error)
calico_felix_log_level: "warning"
# calicoctl 下载地址
calicoctl_url: https://file.choerodon.com.cn/kubernetes/calico/calicoctl/v3.7.2/calicoctl
# calicoctl sha校验码
calicoctl_sha256: ca1a5612d534d785bf191fdbfeed1f6c6eb89d800d990589b2ae09cd07c98634