# 提权操作
ansible_become: true
# 是否启用网络组建
cluster_network_enabled: true
# 默认网络插件
cluster_network: flannel
# 集群pod ip段
kube_pod_subnet: 10.244.0.0/18

# 设置 flannel 后端
# flannel_backend: "host-gw"
flannel_backend: "vxlan"
# flannel 镜像地址
flannel_image: quay.azk8s.cn/coreos/flannel:v0.10.0-amd64
# 选择默认网卡
flannel_iface: true

# calico mtu
calico_veth_mtu: 1440
# calico 相关镜像
calico_typha_image: dockerhub.azk8s.cn/calico/typha:v3.7.2
calico_cni_image: dockerhub.azk8s.cn/calico/cni:v3.7.2
calico_node_image: dockerhub.azk8s.cn/calico/node:v3.7.2
calico_kube_controllers_image: dockerhub.azk8s.cn/calico/kube-controllers:v3.7.2
# 设置 Felix 日志级别(debug, info, warning, error)
calico_felix_log_level: "warning"