- name: Haproxy | 创建 lb 相关目录
  file: 
    name: "{{ item }}"
    state: directory
  with_items:
  - /etc/haproxy
  - /etc/kubernetes/manifests

- name: Haproxy | 拉取相关镜像
  shell: docker pull {{ item }}
  with_items:
  - "{{ kube_haproxy_image }}"
  - "{{ pod_infra_container_image }}"
  when: install_mode == 'online'

- name: Haproxy | 生成 haproxy 配置文件
  template: 
    src: haproxy.cfg.j2 
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    mode: 0644
  register: lb_configuration_result
- name: 设置变量 LB_CONFIGURATION_CHECKSUM
  set_fact: LB_CONFIGURATION_CHECKSUM="{{ lb_configuration_result.checksum }}"

- name: Haproxy | 生成 haproxy static pod 文件
  template: 
    src: haproxy.yaml.j2
    dest: /etc/kubernetes/manifests/lb-kube-apiserver.yaml
    owner: root
    mode: 0644