# 提权操作
ansible_become: true
# kernel repo
kernel_centos:
- http://files.saas.hand-china.com/kernel/centos/kernel-ml-4.20.13-1.el7.elrepo.x86_64.rpm
- http://files.saas.hand-china.com/kernel/centos/kernel-ml-devel-4.20.13-1.el7.elrepo.x86_64.rpm
# - http://mirrors.reposnap.com/elrepo/20190306130017/kernel/el7/x86_64/RPMS/kernel-ml-4.20.13-1.el7.elrepo.x86_64.rpm
# - http://mirrors.reposnap.com/elrepo/20190306130017/kernel/el7/x86_64/RPMS/kernel-ml-devel-4.20.13-1.el7.elrepo.x86_64.rpm

kernel_ubuntu: 
- http://files.saas.hand-china.com/kernel/ubuntu/linux-headers-4.20.17-042017_4.20.17-042017.201903190933_all.deb
- http://files.saas.hand-china.com/kernel/ubuntu/linux-headers-4.20.17-042017-generic_4.20.17-042017.201903190933_amd64.deb
- http://files.saas.hand-china.com/kernel/ubuntu/linux-modules-4.20.17-042017-generic_4.20.17-042017.201903190933_amd64.deb
- http://files.saas.hand-china.com/kernel/ubuntu/linux-image-unsigned-4.20.17-042017-generic_4.20.17-042017.201903190933_amd64.deb
# - http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.20.17/linux-headers-4.20.17-042017_4.20.17-042017.201903190933_all.deb
# - http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.20.17/linux-headers-4.20.17-042017-generic_4.20.17-042017.201903190933_amd64.deb
# - http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.20.17/linux-modules-4.20.17-042017-generic_4.20.17-042017.201903190933_amd64.deb
# - http://kernel.ubuntu.com/~kernel-ppa/mainline/v4.20.17/linux-image-unsigned-4.20.17-042017-generic_4.20.17-042017.201903190933_amd64.deb

linux_base:
- http://files.saas.hand-china.com/kernel/ubuntu/linux-base_4.5ubuntu1.1~16.04.1_all.deb
# - http://security.ubuntu.com/ubuntu/pool/main/l/linux-base/linux-base_4.5ubuntu1.1~16.04.1_all.deb