- include_tasks: common.yml

# - include_tasks: centos.yml
#   when: ansible_distribution in [ 'CentOS','RedHat' ]

# - include_tasks: debian.yml
#   when: ansible_distribution in [ 'Ubuntu','Debian' ]