- name: 添加 Docker apt 仓库
  apt_repository:
    repo: "{{ docker_apt_repo }}"
    state: present

- name: 安装 Docker
  apt: 
    name:
    - "docker-ce={{ docker_version }}{% if docker_version is version_compare('18.09', '<') %}~ce{% endif %}~3-0~{{ ansible_distribution | lower }}"
    state: present
    allow_unauthenticated: true