- name: 添加 Docker apt 仓库
  apt_repository:
    repo: "{{ docker_apt_repo }}"
    state: present

- name: 添加 Docker GPG 公钥
  shell: echo {{ docker_gpg_key }} | apt-key add -

- name: 安装 Docker
  apt: 
    name:
    - "docker-ce={{ docker_version }}~ce~3-0~{{ ansible_distribution | lower }}"
    state: present
    allow_unauthenticated: true
  when: docker_version is version_compare('18.09', '<')

- name: 安装 Docker
  apt: 
    name:
    - "docker-ce=5:{{ docker_version }}~3-0~{{ ansible_distribution | lower }}-{{ ansible_distribution_release }}"
    state: present
    allow_unauthenticated: true
  when: docker_version is version_compare('18.09', '>=')