- name: 校验 hostname 是否合法
  assert:
    that: inventory_hostname == "{{ inventory_hostname|lower }}"
    msg: "hostname 中包含大写字母，请修改为小写后重启服务器再重试。"

- name: 校验 master 节点数量
  run_once: true
  assert:
    that: groups['kube-master'] | length > 1
    msg: "请将添加至少两个节点到 kube-master 节点组中。"

- name: 校验 lb_kube_apiserver_ip 是否合法
  assert:
    that: lb_kube_apiserver_ip != CURRENT_HOST_IP
    msg: "VIP 不能设置为集群节点的 IP。"
  when: lb_kube_apiserver_ip is defined

- block:
  - name: 校验 lb 模式节点设置
    run_once: true
    assert:
      that: "{{ item }}" in groups['all']
      msg: "master 节点数量大于 1，请将所有节点添加至 lb 节点组中。"
    with_items: groups['lb']|unique
  - name: 校验 lb 模式端口设置
    run_once: true
    assert:
      that: lb_kube_apiserver_port != "6443"
      msg: "lb 节点与 master 节点有复用情况，lb_kube_apiserver_port 请勿使用6443端口。"
  when: 
  - (groups['kube-master']|length + groups['new-master']|length) > 1
  - lb_kube_apiserver_ip is not defined

- block:
  - name: 校验 lb 模式节点设置
    run_once: true
    assert:
      that: groups['lb'] | length > 1
      msg: "请将添加至少两个节点到 lb 节点组中。"
  - name: 校验 lb 模式端口设置
    assert:
      that: lb_kube_apiserver_port != "6443"
      msg: "lb 节点与 master 节点有复用情况，lb_kube_apiserver_port 请勿使用6443端口。"
    when:
    - inventory_hostname in ((groups['kube-master'] + groups['new-master'])|unique) 
    - inventory_hostname in groups['lb']
  when: 
  - (groups['kube-master']|length + groups['new-master']|length) > 1
  - lb_kube_apiserver_ip is defined

- name: 校验 etcd 节点数量
  run_once: true
  assert:
    that: groups['etcd'] | length is odd
    msg: "etcd 节点数量必须为奇数，请添加或减少 etcd 节点数量至奇数个。"