- include_tasks: centos.yml
  when: ansible_distribution in [ 'CentOS','RedHat' ]

- include_tasks: ubuntu.yml
  when: ansible_distribution in [ 'Ubuntu','Debian' ]

- debug:
    msg: "内核已升级完成，请手动重启节点：{{ inventory_hostname }} 。"