name: Offline
on: push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Download images
      run: |
        cd $GITHUB_WORKSPACE/offline
        /bin/bash download-images.sh
    - name: Download yum
      run: |
        cd $GITHUB_WORKSPACE/offline
        docker run \
        -v $PWD:/offline \
        -w /offline \
        centos:7 \
        /bin/bash /offline/download-yum.sh
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      run: |
        cd $GITHUB_WORKSPACE/offline
        docker build -t setzero/kubeadm-ha:1.20.1 .
        docker push setzero/kubeadm-ha:1.20.1
        docker save setzero/kubeadm-ha:1.20.1 | gzip -1 > kubeadm-ha-1.20.1.tar
    - name: Upload artifact to oss
      id: oss
      run: |
        sudo apt-get update
        sudo apt-get install jq -y
        curl -sSLo mc https://dl.min.io/client/mc/release/linux-amd64/mc
        chmod +x mc
        ./mc alias set oss https://oss.choerodon.com.cn ${{ secrets.OSS_USERNAME }} ${{ secrets.OSS_TOKEN }}
        ./mc cp --json offline/docker-ce-19.03.13.tar.gz oss/kubeadm-ha 2>&1 | tee oss.log
        target=$(cat oss.log | jq -r 'select(.target)|.target')
        echo "::warning file=docker-ce::https://oss.choerodon.com.cn/${target#*/}"
        ./mc cp --json offline/kubeadm-ha-1.20.1.tar oss/kubeadm-ha 2>&1 | tee oss.log
        target=$(cat oss.log | jq -r 'select(.target)|.target')
        echo "::warning file=kubeadm-ha::https://oss.choerodon.com.cn/${target#*/}"
    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 7
        keep_minimum_runs: 3